# Generated by Django 4.0.4 on 2022-05-12 03:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNum', models.TextField(max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, validators=[django.core.validators.RegexValidator(code='invalid_password', message='Phone number must start 05 and it 10 digit like 05xxxxxxxx', regex='^05[0-9]{8}$')])),
            ],
        ),
    ]
