# Generated by Django 4.0.4 on 2022-05-13 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userinfo_phonenum_alter_userinfo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=70)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
