# Generated by Django 4.0.4 on 2022-05-13 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='message',
            new_name='Contact_message',
        ),
    ]
