# Generated by Django 4.0.4 on 2022-05-14 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_message_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='contact_message',
            name='message',
            field=models.TextField(),
        ),
    ]
