# Generated by Django 4.0.4 on 2022-05-14 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_contact_message_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='Specialist')),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='PhoneNum',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(code='invalid_password', message='Phone number must start 05 and it 10 digit like 05xxxxxxxx', regex='^05[0-9]{8}$')], verbose_name='Phone number'),
        ),
    ]
