# Generated by Django 4.0.4 on 2022-05-15 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_specialist_alter_userinfo_phonenum'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specialist',
            new_name='Specialty',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='specialty',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.specialty'),
        ),
    ]
