# Generated by Django 4.0.4 on 2022-05-15 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='Title',
            new_name='title',
        ),
    ]
