# Generated by Django 4.0.4 on 2022-05-15 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_title_offer_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.specialty'),
        ),
    ]
