# Generated by Django 4.0.4 on 2022-05-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_userinfo_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='image_profile',
            field=models.ImageField(default='image_profile/default_profile.jpg', upload_to='image_profile'),
        ),
    ]
