# Generated by Django 4.0.4 on 2022-05-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_userinfo_image_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Profile Picture', null=True, upload_to='profiles', verbose_name='Profile Picture')),
                ('image_height', models.PositiveIntegerField(blank=True, default='100', editable=False, null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, default='100', editable=False, null=True)),
            ],
        ),
    ]
