# Generated by Django 4.0.4 on 2022-05-22 07:28

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_modelname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelname',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', help_text='Profile Picture', null=True, upload_to='profiles', verbose_name='Profile Picture', width_field='image_width'),
        ),
    ]
