# Generated by Django 4.0.4 on 2022-05-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_modelname_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelname',
            name='image',
            field=models.ImageField(blank=True, help_text='Profile Picture', null=True, upload_to='profiles', verbose_name='Profile Picture'),
        ),
    ]
