# Generated by Django 4.0.4 on 2022-05-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_modelname_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelname',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='modelname',
            name='image_width',
        ),
    ]
