# Generated by Django 4.0.4 on 2022-05-22 11:59

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_modelname_image_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='image_profile',
            field=models.ImageField(blank=True, default='Images_profile/default_profile.jpg', null=True, upload_to='Images_profile', validators=[main.models.validate_image]),
        ),
    ]
