# Generated by Django 4.0.4 on 2022-05-22 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_userinfo_image_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelName',
        ),
    ]
