# Generated by Django 4.0.4 on 2022-05-28 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_userinfo_birthdate_alter_userinfo_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='birthdate',
            new_name='birth_date',
        ),
    ]
