# Generated by Django 4.0.4 on 2022-05-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_rename_birthdate_userinfo_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chronic_condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='chronic_conditions',
            field=models.ManyToManyField(to='main.chronic_condition'),
        ),
    ]
