# Generated by Django 4.0.4 on 2022-05-28 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_chronic_condition_userinfo_chronic_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.specialty'),
        ),
    ]
