# Generated by Django 4.0.4 on 2022-05-29 22:10

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_userinfo_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregister',
            name='file',
            field=models.FileField(upload_to=main.models.random_name('Files')),
        ),
        migrations.AlterField(
            model_name='patientregister',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userinfo'),
        ),
    ]
