# Generated by Django 4.0.4 on 2022-05-30 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_day_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.schedule'),
        ),
    ]
