# Generated by Django 4.0.4 on 2022-05-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_userinfo_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='schedule',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='off_day',
            field=models.ManyToManyField(blank=True, null=True, to='main.day'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='schedule',
        ),
    ]
