# Generated by Django 4.0.4 on 2022-05-31 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_remove_userinfo_schedule_userinfo_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='chronic_conditions',
            field=models.ManyToManyField(blank=True, null=True, to='main.chronic_condition'),
        ),
    ]
