# Generated by Django 4.0.4 on 2022-06-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_userinfo_chronic_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='adate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_from',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_to',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='chronic_conditions',
            field=models.ManyToManyField(blank=True, to='main.chronic_condition'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='off_day',
            field=models.ManyToManyField(blank=True, to='main.day'),
        ),
    ]
