# Generated by Django 4.0.4 on 2022-06-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_appointment_doctor_alter_appointment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(choices=[(1, 'accepted'), (2, 'pended'), (3, 'rejected')], default=1),
            preserve_default=False,
        ),
    ]
