# Generated by Django 4.0.4 on 2022-07-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_userinfo_off_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='off_day',
            field=models.ManyToManyField(blank=True, related_name='off_days', to='main.day'),
        ),
    ]
