# Generated by Django 4.0.4 on 2022-07-26 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_alter_userinfo_off_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregister',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='main.userinfo'),
        ),
    ]
