# Generated by Django 4.0.4 on 2022-07-26 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_patientregister_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientregister',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='main.userinfo'),
        ),
    ]
