# Generated by Django 4.0.4 on 2022-07-26 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_patientregister_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregister',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='main.userinfo'),
        ),
    ]
