# Generated by Django 4.0.4 on 2022-07-30 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_userinfo_ex_address_alter_appointment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregister',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='main.userinfo'),
        ),
    ]
